name: PkShopkeepers
version: 1.6
main: com.pumpkings.pkshopkeepers.PkShopkeepers
api-version: '1.21'
description: A modern re-implementation of Shopkeepers
author: Pumpkings

folia-supported: true

dependencies:
  server:
    FancyNpcs:
      load: BEFORE
      required: false
    Shopkeepers:
      load: BEFORE
      required: false
